name: ci
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  tests:
    name: test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: 1.17.0
            otp: 27.0
          - elixir: 1.16.3
            otp: 26.1.2
          - elixir: 1.15.6
            otp: 24.3.4.13
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - run: docker compose -f "test/compose_files/docker-compose.yml" up -d
      - run: mix deps.get
      - run: mix compile --warnings-as-errors
      - run: mix test --warnings-as-errors